easy_admin:
    design:



        form_theme: 'Form/fields.html.twig'
        menu:
        - { label: 'acceuil', url: 'home', rel: 'index' , icon : "home", default: true}
        # - { label: 'emploi', url: 'emploi', rel: 'emploi' , icon : "home"}
        # - { label: 'list des emploi', url: 'emplois', rel: 'emplois' , icon : "home"}
        - {label: "Global"}
        - label: "Les Matieres"
          icon : "book-reader"

          children:
            - {entity: Matiere, label: "liste des matières", icon: "th-list"}
            - {entity: Matiere, label: "Ajouter Matière", icon: "plus", params: {action: 'new'}}

        - label: "Les Enseignants"
          icon : "chalkboard-teacher"
          children:
            - {entity: Enseignant, label: "List enseignats", icon: "th-list"}
            - {entity: Enseignant, label: "Ajouter un enseignant", icon: "plus",params: {action: 'new'}}
            - {entity: EnseignantDispo, label: "Disponibiltés", icon: "pencil"}
            - {entity: Disponibile, label: "jours et seances", icon: "th-list"}



        - {label: "Gestion des classes"}


        - label: "Les Promotions"
          icon : "calendar-alt"
          children:
            - {entity: Promotion, label: "liste des promotions", icon: "th-list"}
            - {entity: Promotion, label: "Ajouter un promotion", icon: "plus", params: {action: 'new'}}



        - label: "Les Specialites"
          icon : "address-card"
          children:
            - {entity: Specialite, label: "liste des specialités", icon: "th-list"}
            - {entity: Specialite, label: "Ajouter un specialité", icon: "plus", params: {action: 'new'}}

        - label: "Les Classes"
          icon : "chalkboard"

          children:
            - {entity: Groupe, label: "liste des groupe", icon: "th-list"}
            - {entity: Groupe, label: "Ajouter un groupe", icon: "plus", params: {action: 'new'}}

        - label: "Les Emplois"
          icon : "chalkboard"

          children:
            - { label: 'list des emploi', url: 'emplois', rel: 'emplois' , icon : "th-list"}
            - {entity: Emploi, label: "Ajouter un Emploi", icon: "plus", params: {action: 'new'}}


        - {label: "Affectations des matières"}
        - {entity: Affecter,label: 'Affectations', icon: "pencil"}

        - {label: "Paramètres"}
        - {entity: User,label: 'Utilisateurs', icon: "user" ,permission: 'ROLE_ADMIN'}




    site_name: '<img src="../images/logoEcole.png" id="icon" width="10%" alt="User Icon" />    Gestion des emplois du temps'
    user:
        display_name: false
        display_avatar: true
        name_property_path: 'email'
   
   
   
   
    entities:
        # List the entity class name you want to manage

        Matiere:
          class: App\Entity\Matiere
          list:
            fields:
              - Nom_matiere
              - NhTHC
              - NhTD
              - NhTP
              - coefMatiere 
              - Niveau
              - semestre
              - NhTotal
            
        User:
          class: App\Entity\User
          form:
            fields:
              - email
              # if administrators are allowed to edit users' passwords and roles, add this:
              - { property: 'Password', type: 'password', type_options: { required: true } }
              - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
          edit:
            fields:
              - email

            
          list:
            item_permission: 'ROLE_ADMIN'
            fields:
              - email

         

        Promotion:
            class: App\Entity\Promotion
            list:
              fields:
                - designation
                - dateArrive


        Specialite:
            class: App\Entity\Specialite
            list:
              fields:
                - designation


        Groupe:
            class: App\Entity\Groupe
            list:
              fields:
                - niveau
                - nbeleve
                - specialite
                - nom
                - promotion

        Affecter:
            class: App\Entity\Affecter
            list:
              fields:
                - matiere
                - groupe
                - enseignant


        Enseignant:
            class: App\Entity\Enseignant
            label: "Enseignant"
            form:
                fields:
                    - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-7'}
                    - nom_enseignant
                    - prenom_enseignant
                    - Grade
                    - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-5'}
                    - numTel
                    - lieu_travail
                    - Cin
                    - {type: 'group', icon: 'th-list', label: 'Disponibles', css_class: ''}
                    - { property: 'disponibles', type_options: { 'by_reference': false } }

            list :
                actions: ['show', 'edit', 'delete']
                fields:
                    - nom_enseignant
                    - prenom_enseignant
                    - Grade
                    - numTel
                    - lieu_travail
                    - Cin
                    - disponibles


        EnseignantDispo:
            class: App\Entity\Enseignant
            label: "Enseignant"
            edit:
                fields:
                    - { property: 'disponibles', type_options: { 'by_reference': false } }
            list :
                actions:
                  - {name: 'new' , label: ''}
                  - {name: 'edit' , label: 'modifier disponibiltés'}
                  - {name: 'delete' , label: ''}
                fields:
                    - nom_enseignant
                    - prenom_enseignant
                    - Cin
                    - disponibles

                    
        Disponibile:
            class: App\Entity\Disponibile
            list:
              collapse_actions: false
              title: "jours et seances"
              actions: 
                - {name: 'new' , label: 'ajouter un seance'}    
              fields:
                  - jour
                  - Seance
            
            form:
              fields:
                  - jour
                  - Seance
        Emploi:
            class: App\Entity\Emploi
            list:
              collapse_actions: true
              fields:
                  - dateDebut
                  - DateFin
                  - classe
            new:
              fields:
                  - dateDebut
                  # - DateFin
                  - classe
                  - semestre
        DetailsEmploi:
            class: App\Entity\DetailsEmploi
            edit:
              fields:
                  - Matiere
                  - autre
                  
                  # - matieres
                  # - { property: 'matieres', type: 'choice' }




           
             

  
